name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0
    - name: Install NPM
      run: |
        npm install
        
    # Install the SFDX CLI using npm command
    - name: Install the SFDX CLI
      run: |
        npm install sfdx-cli --global
        sfdx force --help
    - name: Update the SFDX CLI
      run: |
        npm update sfdx-cli --global
        sfdx force --help
    - name: Decrypt the Encrypted FIle
      run: |
        openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out ${{secrets.KEY_FILE_PATH}} -base64 -K ${{secrets.KEY}} -iv ${{secrets.IV}}
    - name: Authenticate with Salesforce
      run: |
        sfdx auth:jwt:grant --clientid ${{secrets.CLIENT_KEY}} --jwtkeyfile ${{secrets.KEY_FILE_PATH}} --username ${{secrets.SF_USER_NAME}} --setdefaultdevhubusername --setalias my-hub-org
        
        
